// Generated by gencpp from file sineva_nav/BaseCommandRequest.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_BASECOMMANDREQUEST_H
#define SINEVA_NAV_MESSAGE_BASECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct BaseCommandRequest_
{
  typedef BaseCommandRequest_<ContainerAllocator> Type;

  BaseCommandRequest_()
    : cmd(0)
    , data()  {
    }
  BaseCommandRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BaseCommandRequest_

typedef ::sineva_nav::BaseCommandRequest_<std::allocator<void> > BaseCommandRequest;

typedef boost::shared_ptr< ::sineva_nav::BaseCommandRequest > BaseCommandRequestPtr;
typedef boost::shared_ptr< ::sineva_nav::BaseCommandRequest const> BaseCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::BaseCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::BaseCommandRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::BaseCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::BaseCommandRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::BaseCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73dd2c4617c3899c74e47e69089ecb29";
  }

  static const char* value(const ::sineva_nav::BaseCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73dd2c4617c3899cULL;
  static const uint64_t static_value2 = 0x74e47e69089ecb29ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/BaseCommandRequest";
  }

  static const char* value(const ::sineva_nav::BaseCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 cmd\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::sineva_nav::BaseCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BaseCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::BaseCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::BaseCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_BASECOMMANDREQUEST_H
