// Generated by gencpp from file sineva_nav/CheckGoalStatusSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_CHECKGOALSTATUSSRV_H
#define SINEVA_NAV_MESSAGE_CHECKGOALSTATUSSRV_H

#include <ros/service_traits.h>


#include <sineva_nav/CheckGoalStatusSrvRequest.h>
#include <sineva_nav/CheckGoalStatusSrvResponse.h>


namespace sineva_nav
{

struct CheckGoalStatusSrv
{

typedef CheckGoalStatusSrvRequest Request;
typedef CheckGoalStatusSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckGoalStatusSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::CheckGoalStatusSrv > {
  static const char* value()
  {
    return "3d638b2cdc898e8eb5d6b3cfc2f2c14b";
  }

  static const char* value(const ::sineva_nav::CheckGoalStatusSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::CheckGoalStatusSrv > {
  static const char* value()
  {
    return "sineva_nav/CheckGoalStatusSrv";
  }

  static const char* value(const ::sineva_nav::CheckGoalStatusSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::CheckGoalStatusSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::CheckGoalStatusSrv >
template<>
struct MD5Sum< ::sineva_nav::CheckGoalStatusSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CheckGoalStatusSrv >::value();
  }
  static const char* value(const ::sineva_nav::CheckGoalStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CheckGoalStatusSrvRequest> should match
// service_traits::DataType< ::sineva_nav::CheckGoalStatusSrv >
template<>
struct DataType< ::sineva_nav::CheckGoalStatusSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CheckGoalStatusSrv >::value();
  }
  static const char* value(const ::sineva_nav::CheckGoalStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::CheckGoalStatusSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::CheckGoalStatusSrv >
template<>
struct MD5Sum< ::sineva_nav::CheckGoalStatusSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CheckGoalStatusSrv >::value();
  }
  static const char* value(const ::sineva_nav::CheckGoalStatusSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CheckGoalStatusSrvResponse> should match
// service_traits::DataType< ::sineva_nav::CheckGoalStatusSrv >
template<>
struct DataType< ::sineva_nav::CheckGoalStatusSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CheckGoalStatusSrv >::value();
  }
  static const char* value(const ::sineva_nav::CheckGoalStatusSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_CHECKGOALSTATUSSRV_H
