// Generated by gencpp from file sineva_nav/CloseSafeAreaSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_CLOSESAFEAREASRV_H
#define SINEVA_NAV_MESSAGE_CLOSESAFEAREASRV_H

#include <ros/service_traits.h>


#include <sineva_nav/CloseSafeAreaSrvRequest.h>
#include <sineva_nav/CloseSafeAreaSrvResponse.h>


namespace sineva_nav
{

struct CloseSafeAreaSrv
{

typedef CloseSafeAreaSrvRequest Request;
typedef CloseSafeAreaSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CloseSafeAreaSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::CloseSafeAreaSrv > {
  static const char* value()
  {
    return "453c8349175735b023f9d38fc609cbe6";
  }

  static const char* value(const ::sineva_nav::CloseSafeAreaSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::CloseSafeAreaSrv > {
  static const char* value()
  {
    return "sineva_nav/CloseSafeAreaSrv";
  }

  static const char* value(const ::sineva_nav::CloseSafeAreaSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::CloseSafeAreaSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::CloseSafeAreaSrv >
template<>
struct MD5Sum< ::sineva_nav::CloseSafeAreaSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CloseSafeAreaSrv >::value();
  }
  static const char* value(const ::sineva_nav::CloseSafeAreaSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CloseSafeAreaSrvRequest> should match
// service_traits::DataType< ::sineva_nav::CloseSafeAreaSrv >
template<>
struct DataType< ::sineva_nav::CloseSafeAreaSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CloseSafeAreaSrv >::value();
  }
  static const char* value(const ::sineva_nav::CloseSafeAreaSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::CloseSafeAreaSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::CloseSafeAreaSrv >
template<>
struct MD5Sum< ::sineva_nav::CloseSafeAreaSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CloseSafeAreaSrv >::value();
  }
  static const char* value(const ::sineva_nav::CloseSafeAreaSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CloseSafeAreaSrvResponse> should match
// service_traits::DataType< ::sineva_nav::CloseSafeAreaSrv >
template<>
struct DataType< ::sineva_nav::CloseSafeAreaSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CloseSafeAreaSrv >::value();
  }
  static const char* value(const ::sineva_nav::CloseSafeAreaSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_CLOSESAFEAREASRV_H
