// Generated by gencpp from file sineva_nav/CloseSafeAreaSrvRequest.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_CLOSESAFEAREASRVREQUEST_H
#define SINEVA_NAV_MESSAGE_CLOSESAFEAREASRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct CloseSafeAreaSrvRequest_
{
  typedef CloseSafeAreaSrvRequest_<ContainerAllocator> Type;

  CloseSafeAreaSrvRequest_()
    : enable(0)  {
    }
  CloseSafeAreaSrvRequest_(const ContainerAllocator& _alloc)
    : enable(0)  {
  (void)_alloc;
    }



   typedef int32_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CloseSafeAreaSrvRequest_

typedef ::sineva_nav::CloseSafeAreaSrvRequest_<std::allocator<void> > CloseSafeAreaSrvRequest;

typedef boost::shared_ptr< ::sineva_nav::CloseSafeAreaSrvRequest > CloseSafeAreaSrvRequestPtr;
typedef boost::shared_ptr< ::sineva_nav::CloseSafeAreaSrvRequest const> CloseSafeAreaSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7d7302aaa1be3c7095acb91a001edf8";
  }

  static const char* value(const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7d7302aaa1be3c7ULL;
  static const uint64_t static_value2 = 0x095acb91a001edf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/CloseSafeAreaSrvRequest";
  }

  static const char* value(const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# request message\n"
"int32 enable\n"
;
  }

  static const char* value(const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CloseSafeAreaSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::CloseSafeAreaSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<int32_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_CLOSESAFEAREASRVREQUEST_H
