// Generated by gencpp from file sineva_nav/GetStateSrvResponse.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_GETSTATESRVRESPONSE_H
#define SINEVA_NAV_MESSAGE_GETSTATESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct GetStateSrvResponse_
{
  typedef GetStateSrvResponse_<ContainerAllocator> Type;

  GetStateSrvResponse_()
    : goal_id()
    , status_code(0)  {
    }
  GetStateSrvResponse_(const ContainerAllocator& _alloc)
    : goal_id(_alloc)
    , status_code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_id_type;
  _goal_id_type goal_id;

   typedef int32_t _status_code_type;
  _status_code_type status_code;





  typedef boost::shared_ptr< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStateSrvResponse_

typedef ::sineva_nav::GetStateSrvResponse_<std::allocator<void> > GetStateSrvResponse;

typedef boost::shared_ptr< ::sineva_nav::GetStateSrvResponse > GetStateSrvResponsePtr;
typedef boost::shared_ptr< ::sineva_nav::GetStateSrvResponse const> GetStateSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal_id == rhs.goal_id &&
    lhs.status_code == rhs.status_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20302303840f9550e869dd96dba66a06";
  }

  static const char* value(const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20302303840f9550ULL;
  static const uint64_t static_value2 = 0xe869dd96dba66a06ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/GetStateSrvResponse";
  }

  static const char* value(const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response message\n"
"string goal_id\n"
"int32 status_code\n"
"\n"
;
  }

  static const char* value(const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_id);
      stream.next(m.status_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStateSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::GetStateSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::GetStateSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_id);
    s << indent << "status_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_GETSTATESRVRESPONSE_H
