// Generated by gencpp from file sineva_nav/JsonSrvResponse.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_JSONSRVRESPONSE_H
#define SINEVA_NAV_MESSAGE_JSONSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct JsonSrvResponse_
{
  typedef JsonSrvResponse_<ContainerAllocator> Type;

  JsonSrvResponse_()
    : result(0)
    , dataRes()  {
    }
  JsonSrvResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , dataRes(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dataRes_type;
  _dataRes_type dataRes;





  typedef boost::shared_ptr< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JsonSrvResponse_

typedef ::sineva_nav::JsonSrvResponse_<std::allocator<void> > JsonSrvResponse;

typedef boost::shared_ptr< ::sineva_nav::JsonSrvResponse > JsonSrvResponsePtr;
typedef boost::shared_ptr< ::sineva_nav::JsonSrvResponse const> JsonSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::JsonSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::JsonSrvResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::JsonSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.dataRes == rhs.dataRes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::JsonSrvResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::JsonSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e569e7fbed8aa082ed65e56493a1cb29";
  }

  static const char* value(const ::sineva_nav::JsonSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe569e7fbed8aa082ULL;
  static const uint64_t static_value2 = 0xed65e56493a1cb29ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/JsonSrvResponse";
  }

  static const char* value(const ::sineva_nav::JsonSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# response message\n"
"int32 result\n"
"string dataRes\n"
;
  }

  static const char* value(const ::sineva_nav::JsonSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.dataRes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JsonSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::JsonSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::JsonSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "dataRes: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dataRes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_JSONSRVRESPONSE_H
