// Generated by gencpp from file sineva_nav/JsonCommSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_JSONCOMMSRV_H
#define SINEVA_NAV_MESSAGE_JSONCOMMSRV_H

#include <ros/service_traits.h>


#include <sineva_nav/JsonCommSrvRequest.h>
#include <sineva_nav/JsonCommSrvResponse.h>


namespace sineva_nav
{

struct JsonCommSrv
{

typedef JsonCommSrvRequest Request;
typedef JsonCommSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JsonCommSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::JsonCommSrv > {
  static const char* value()
  {
    return "ca17d783c86e928bc4beab3674acd9b4";
  }

  static const char* value(const ::sineva_nav::JsonCommSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::JsonCommSrv > {
  static const char* value()
  {
    return "sineva_nav/JsonCommSrv";
  }

  static const char* value(const ::sineva_nav::JsonCommSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::JsonCommSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::JsonCommSrv >
template<>
struct MD5Sum< ::sineva_nav::JsonCommSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::JsonCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::JsonCommSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::JsonCommSrvRequest> should match
// service_traits::DataType< ::sineva_nav::JsonCommSrv >
template<>
struct DataType< ::sineva_nav::JsonCommSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::JsonCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::JsonCommSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::JsonCommSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::JsonCommSrv >
template<>
struct MD5Sum< ::sineva_nav::JsonCommSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::JsonCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::JsonCommSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::JsonCommSrvResponse> should match
// service_traits::DataType< ::sineva_nav::JsonCommSrv >
template<>
struct DataType< ::sineva_nav::JsonCommSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::JsonCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::JsonCommSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_JSONCOMMSRV_H
