// Generated by gencpp from file sineva_nav/manage_charge.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_MANAGE_CHARGE_H
#define SINEVA_NAV_MESSAGE_MANAGE_CHARGE_H

#include <ros/service_traits.h>


#include <sineva_nav/manage_chargeRequest.h>
#include <sineva_nav/manage_chargeResponse.h>


namespace sineva_nav
{

struct manage_charge
{

typedef manage_chargeRequest Request;
typedef manage_chargeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct manage_charge
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::manage_charge > {
  static const char* value()
  {
    return "a5c10a0299cfe8117c94010efa5c0025";
  }

  static const char* value(const ::sineva_nav::manage_charge&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::manage_charge > {
  static const char* value()
  {
    return "sineva_nav/manage_charge";
  }

  static const char* value(const ::sineva_nav::manage_charge&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::manage_chargeRequest> should match
// service_traits::MD5Sum< ::sineva_nav::manage_charge >
template<>
struct MD5Sum< ::sineva_nav::manage_chargeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::manage_charge >::value();
  }
  static const char* value(const ::sineva_nav::manage_chargeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::manage_chargeRequest> should match
// service_traits::DataType< ::sineva_nav::manage_charge >
template<>
struct DataType< ::sineva_nav::manage_chargeRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::manage_charge >::value();
  }
  static const char* value(const ::sineva_nav::manage_chargeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::manage_chargeResponse> should match
// service_traits::MD5Sum< ::sineva_nav::manage_charge >
template<>
struct MD5Sum< ::sineva_nav::manage_chargeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::manage_charge >::value();
  }
  static const char* value(const ::sineva_nav::manage_chargeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::manage_chargeResponse> should match
// service_traits::DataType< ::sineva_nav::manage_charge >
template<>
struct DataType< ::sineva_nav::manage_chargeResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::manage_charge >::value();
  }
  static const char* value(const ::sineva_nav::manage_chargeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_MANAGE_CHARGE_H
