// Generated by gencpp from file sineva_nav/manage_map_lidarResponse.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_MANAGE_MAP_LIDARRESPONSE_H
#define SINEVA_NAV_MESSAGE_MANAGE_MAP_LIDARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace sineva_nav
{
template <class ContainerAllocator>
struct manage_map_lidarResponse_
{
  typedef manage_map_lidarResponse_<ContainerAllocator> Type;

  manage_map_lidarResponse_()
    : result(false)
    , mapId()
    , pose()  {
    }
  manage_map_lidarResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , mapId(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapId_type;
  _mapId_type mapId;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> const> ConstPtr;

}; // struct manage_map_lidarResponse_

typedef ::sineva_nav::manage_map_lidarResponse_<std::allocator<void> > manage_map_lidarResponse;

typedef boost::shared_ptr< ::sineva_nav::manage_map_lidarResponse > manage_map_lidarResponsePtr;
typedef boost::shared_ptr< ::sineva_nav::manage_map_lidarResponse const> manage_map_lidarResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.mapId == rhs.mapId &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator1> & lhs, const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29612251d79506cf4df2e11bbf13f61d";
  }

  static const char* value(const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29612251d79506cfULL;
  static const uint64_t static_value2 = 0x4df2e11bbf13f61dULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/manage_map_lidarResponse";
  }

  static const char* value(const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"string mapId\n"
"geometry_msgs/Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.mapId);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct manage_map_lidarResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::manage_map_lidarResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "mapId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapId);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_MANAGE_MAP_LIDARRESPONSE_H
