// Generated by gencpp from file sineva_nav/SetInitialPoseSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_SETINITIALPOSESRV_H
#define SINEVA_NAV_MESSAGE_SETINITIALPOSESRV_H

#include <ros/service_traits.h>


#include <sineva_nav/SetInitialPoseSrvRequest.h>
#include <sineva_nav/SetInitialPoseSrvResponse.h>


namespace sineva_nav
{

struct SetInitialPoseSrv
{

typedef SetInitialPoseSrvRequest Request;
typedef SetInitialPoseSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialPoseSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::SetInitialPoseSrv > {
  static const char* value()
  {
    return "f79b49745aeb97ecd996566018ba09e8";
  }

  static const char* value(const ::sineva_nav::SetInitialPoseSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::SetInitialPoseSrv > {
  static const char* value()
  {
    return "sineva_nav/SetInitialPoseSrv";
  }

  static const char* value(const ::sineva_nav::SetInitialPoseSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::SetInitialPoseSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::SetInitialPoseSrv >
template<>
struct MD5Sum< ::sineva_nav::SetInitialPoseSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SetInitialPoseSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetInitialPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SetInitialPoseSrvRequest> should match
// service_traits::DataType< ::sineva_nav::SetInitialPoseSrv >
template<>
struct DataType< ::sineva_nav::SetInitialPoseSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SetInitialPoseSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetInitialPoseSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::SetInitialPoseSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::SetInitialPoseSrv >
template<>
struct MD5Sum< ::sineva_nav::SetInitialPoseSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SetInitialPoseSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetInitialPoseSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SetInitialPoseSrvResponse> should match
// service_traits::DataType< ::sineva_nav::SetInitialPoseSrv >
template<>
struct DataType< ::sineva_nav::SetInitialPoseSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SetInitialPoseSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetInitialPoseSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_SETINITIALPOSESRV_H
