// Generated by gencpp from file sineva_nav/SetPositionsSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_SETPOSITIONSSRV_H
#define SINEVA_NAV_MESSAGE_SETPOSITIONSSRV_H

#include <ros/service_traits.h>


#include <sineva_nav/SetPositionsSrvRequest.h>
#include <sineva_nav/SetPositionsSrvResponse.h>


namespace sineva_nav
{

struct SetPositionsSrv
{

typedef SetPositionsSrvRequest Request;
typedef SetPositionsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPositionsSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::SetPositionsSrv > {
  static const char* value()
  {
    return "4b4524857e30c20d60b58e736d911c02";
  }

  static const char* value(const ::sineva_nav::SetPositionsSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::SetPositionsSrv > {
  static const char* value()
  {
    return "sineva_nav/SetPositionsSrv";
  }

  static const char* value(const ::sineva_nav::SetPositionsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::SetPositionsSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::SetPositionsSrv >
template<>
struct MD5Sum< ::sineva_nav::SetPositionsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SetPositionsSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetPositionsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SetPositionsSrvRequest> should match
// service_traits::DataType< ::sineva_nav::SetPositionsSrv >
template<>
struct DataType< ::sineva_nav::SetPositionsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SetPositionsSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetPositionsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::SetPositionsSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::SetPositionsSrv >
template<>
struct MD5Sum< ::sineva_nav::SetPositionsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SetPositionsSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetPositionsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SetPositionsSrvResponse> should match
// service_traits::DataType< ::sineva_nav::SetPositionsSrv >
template<>
struct DataType< ::sineva_nav::SetPositionsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SetPositionsSrv >::value();
  }
  static const char* value(const ::sineva_nav::SetPositionsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_SETPOSITIONSSRV_H
