// Generated by gencpp from file sineva_nav/SlamStatus.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_SLAMSTATUS_H
#define SINEVA_NAV_MESSAGE_SLAMSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sineva_nav
{
template <class ContainerAllocator>
struct SlamStatus_
{
  typedef SlamStatus_<ContainerAllocator> Type;

  SlamStatus_()
    : header()
    , status()
    , result(false)
    , information(0.0)  {
    }
  SlamStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , result(false)
    , information(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef uint8_t _result_type;
  _result_type result;

   typedef float _information_type;
  _information_type information;





  typedef boost::shared_ptr< ::sineva_nav::SlamStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::SlamStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SlamStatus_

typedef ::sineva_nav::SlamStatus_<std::allocator<void> > SlamStatus;

typedef boost::shared_ptr< ::sineva_nav::SlamStatus > SlamStatusPtr;
typedef boost::shared_ptr< ::sineva_nav::SlamStatus const> SlamStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::SlamStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::SlamStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::SlamStatus_<ContainerAllocator1> & lhs, const ::sineva_nav::SlamStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.result == rhs.result &&
    lhs.information == rhs.information;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::SlamStatus_<ContainerAllocator1> & lhs, const ::sineva_nav::SlamStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::SlamStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::SlamStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::SlamStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::SlamStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::SlamStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::SlamStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::SlamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7626330be62699453af28c97dc15917";
  }

  static const char* value(const ::sineva_nav::SlamStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7626330be626994ULL;
  static const uint64_t static_value2 = 0x53af28c97dc15917ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::SlamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/SlamStatus";
  }

  static const char* value(const ::sineva_nav::SlamStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::SlamStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string          status      # Current status\n"
"bool            result      # Success or failed\n"
"float32         information # Other information\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sineva_nav::SlamStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::SlamStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.result);
      stream.next(m.information);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::SlamStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::SlamStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "information: ";
    Printer<float>::stream(s, indent + "  ", v.information);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_SLAMSTATUS_H
