// Generated by gencpp from file sineva_nav/StringCommSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_STRINGCOMMSRV_H
#define SINEVA_NAV_MESSAGE_STRINGCOMMSRV_H

#include <ros/service_traits.h>


#include <sineva_nav/StringCommSrvRequest.h>
#include <sineva_nav/StringCommSrvResponse.h>


namespace sineva_nav
{

struct StringCommSrv
{

typedef StringCommSrvRequest Request;
typedef StringCommSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringCommSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::StringCommSrv > {
  static const char* value()
  {
    return "ca17d783c86e928bc4beab3674acd9b4";
  }

  static const char* value(const ::sineva_nav::StringCommSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::StringCommSrv > {
  static const char* value()
  {
    return "sineva_nav/StringCommSrv";
  }

  static const char* value(const ::sineva_nav::StringCommSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::StringCommSrvRequest> should match
// service_traits::MD5Sum< ::sineva_nav::StringCommSrv >
template<>
struct MD5Sum< ::sineva_nav::StringCommSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::StringCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::StringCommSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::StringCommSrvRequest> should match
// service_traits::DataType< ::sineva_nav::StringCommSrv >
template<>
struct DataType< ::sineva_nav::StringCommSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::StringCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::StringCommSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::StringCommSrvResponse> should match
// service_traits::MD5Sum< ::sineva_nav::StringCommSrv >
template<>
struct MD5Sum< ::sineva_nav::StringCommSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::StringCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::StringCommSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::StringCommSrvResponse> should match
// service_traits::DataType< ::sineva_nav::StringCommSrv >
template<>
struct DataType< ::sineva_nav::StringCommSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::StringCommSrv >::value();
  }
  static const char* value(const ::sineva_nav::StringCommSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_STRINGCOMMSRV_H
