// Generated by gencpp from file sineva_nav/UpdateMapSrvRequest.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_UPDATEMAPSRVREQUEST_H
#define SINEVA_NAV_MESSAGE_UPDATEMAPSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/OccupancyGrid.h>

namespace sineva_nav
{
template <class ContainerAllocator>
struct UpdateMapSrvRequest_
{
  typedef UpdateMapSrvRequest_<ContainerAllocator> Type;

  UpdateMapSrvRequest_()
    : mapDate()  {
    }
  UpdateMapSrvRequest_(const ContainerAllocator& _alloc)
    : mapDate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _mapDate_type;
  _mapDate_type mapDate;





  typedef boost::shared_ptr< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateMapSrvRequest_

typedef ::sineva_nav::UpdateMapSrvRequest_<std::allocator<void> > UpdateMapSrvRequest;

typedef boost::shared_ptr< ::sineva_nav::UpdateMapSrvRequest > UpdateMapSrvRequestPtr;
typedef boost::shared_ptr< ::sineva_nav::UpdateMapSrvRequest const> UpdateMapSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mapDate == rhs.mapDate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator1> & lhs, const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sineva_nav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e276c0a971ae6c97456d10dab0f807f";
  }

  static const char* value(const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e276c0a971ae6c9ULL;
  static const uint64_t static_value2 = 0x7456d10dab0f807fULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/UpdateMapSrvRequest";
  }

  static const char* value(const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/OccupancyGrid mapDate\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/OccupancyGrid\n"
"# This represents a 2-D grid map, in which each cell represents the probability of\n"
"# occupancy.\n"
"\n"
"Header header \n"
"\n"
"#MetaData for the map\n"
"MapMetaData info\n"
"\n"
"# The map data, in row-major order, starting with (0,0).  Occupancy\n"
"# probabilities are in the range [0,100].  Unknown is -1.\n"
"int8[] data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/MapMetaData\n"
"# This hold basic information about the characterists of the OccupancyGrid\n"
"\n"
"# The time at which the map was loaded\n"
"time map_load_time\n"
"# The map resolution [m/cell]\n"
"float32 resolution\n"
"# Map width [cells]\n"
"uint32 width\n"
"# Map height [cells]\n"
"uint32 height\n"
"# The origin of the map [m, m, rad].  This is the real-world pose of the\n"
"# cell (0,0) in the map.\n"
"geometry_msgs/Pose origin\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapDate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateMapSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::UpdateMapSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapDate: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.mapDate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_UPDATEMAPSRVREQUEST_H
