#for a given target and map return the found path
mpac_msgs/RobotTarget target
nav_msgs/OccupancyGrid map
mpac_msgs/VectorMap vector_map
mpac_msgs/GeoFence geofence
float32 max_planning_time
mpac_msgs/PlanParameters plan_parameters
mpac_msgs/RobotConfigs robot_configs
---
mpac_msgs/Path path
mpac_msgs/Paths paths
nav_msgs/Path path_pub
mpac_msgs/PathParameters params
bool valid
int32 PathGetMethod #0--free  1--track
