// Generated by gencpp from file sineva_nav/RelocationRequest.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_RELOCATIONREQUEST_H
#define SINEVA_NAV_MESSAGE_RELOCATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct RelocationRequest_
{
  typedef RelocationRequest_<ContainerAllocator> Type;

  RelocationRequest_()
    : mapId()
    , flag()  {
    }
  RelocationRequest_(const ContainerAllocator& _alloc)
    : mapId(_alloc)
    , flag(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapId_type;
  _mapId_type mapId;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::sineva_nav::RelocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::RelocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelocationRequest_

typedef ::sineva_nav::RelocationRequest_<std::allocator<void> > RelocationRequest;

typedef boost::shared_ptr< ::sineva_nav::RelocationRequest > RelocationRequestPtr;
typedef boost::shared_ptr< ::sineva_nav::RelocationRequest const> RelocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::RelocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::RelocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sineva_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sineva_nav': ['/home/nuc/code/Sineva_Code-delivery/ssp/ros/src/sineva_nav/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::RelocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::RelocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::RelocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c80659962eba898744da014535f5748";
  }

  static const char* value(const ::sineva_nav::RelocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c80659962eba898ULL;
  static const uint64_t static_value2 = 0x744da014535f5748ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/RelocationRequest";
  }

  static const char* value(const ::sineva_nav::RelocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapId\n\
string flag\n\
";
  }

  static const char* value(const ::sineva_nav::RelocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapId);
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::RelocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::RelocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapId: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapId);
    s << indent << "flag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_RELOCATIONREQUEST_H
