// Generated by gencpp from file sineva_nav/CancelGoalSrv.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_CANCELGOALSRV_H
#define SINEVA_NAV_MESSAGE_CANCELGOALSRV_H

#include <ros/service_traits.h>


#include <sineva_nav/CancelGoalSrvRequest.h>
#include <sineva_nav/CancelGoalSrvResponse.h>


namespace sineva_nav
{

struct CancelGoalSrv
{

typedef CancelGoalSrvRequest Request;
typedef CancelGoalSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CancelGoalSrv
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::CancelGoalSrv > {
  static const char* value()
  {
    return "69b4ce7997dd89357a2ebdc1827d4b0d";
  }

  static const char* value(const ::sineva_nav::CancelGoalSrv&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::CancelGoalSrv > {
  static const char* value()
  {
    return "sineva_nav/CancelGoalSrv";
  }

  static const char* value(const ::sineva_nav::CancelGoalSrv&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::CancelGoalSrvRequest> should match 
// service_traits::MD5Sum< ::sineva_nav::CancelGoalSrv > 
template<>
struct MD5Sum< ::sineva_nav::CancelGoalSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CancelGoalSrv >::value();
  }
  static const char* value(const ::sineva_nav::CancelGoalSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CancelGoalSrvRequest> should match 
// service_traits::DataType< ::sineva_nav::CancelGoalSrv > 
template<>
struct DataType< ::sineva_nav::CancelGoalSrvRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CancelGoalSrv >::value();
  }
  static const char* value(const ::sineva_nav::CancelGoalSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::CancelGoalSrvResponse> should match 
// service_traits::MD5Sum< ::sineva_nav::CancelGoalSrv > 
template<>
struct MD5Sum< ::sineva_nav::CancelGoalSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::CancelGoalSrv >::value();
  }
  static const char* value(const ::sineva_nav::CancelGoalSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::CancelGoalSrvResponse> should match 
// service_traits::DataType< ::sineva_nav::CancelGoalSrv > 
template<>
struct DataType< ::sineva_nav::CancelGoalSrvResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::CancelGoalSrv >::value();
  }
  static const char* value(const ::sineva_nav::CancelGoalSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_CANCELGOALSRV_H
