// Generated by gencpp from file sineva_nav/Relocation.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_RELOCATION_H
#define SINEVA_NAV_MESSAGE_RELOCATION_H

#include <ros/service_traits.h>


#include <sineva_nav/RelocationRequest.h>
#include <sineva_nav/RelocationResponse.h>


namespace sineva_nav
{

struct Relocation
{

typedef RelocationRequest Request;
typedef RelocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Relocation
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::Relocation > {
  static const char* value()
  {
    return "82f1b53ec405d751bfebc95a42bfd76d";
  }

  static const char* value(const ::sineva_nav::Relocation&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::Relocation > {
  static const char* value()
  {
    return "sineva_nav/Relocation";
  }

  static const char* value(const ::sineva_nav::Relocation&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::RelocationRequest> should match 
// service_traits::MD5Sum< ::sineva_nav::Relocation > 
template<>
struct MD5Sum< ::sineva_nav::RelocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::Relocation >::value();
  }
  static const char* value(const ::sineva_nav::RelocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::RelocationRequest> should match 
// service_traits::DataType< ::sineva_nav::Relocation > 
template<>
struct DataType< ::sineva_nav::RelocationRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::Relocation >::value();
  }
  static const char* value(const ::sineva_nav::RelocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::RelocationResponse> should match 
// service_traits::MD5Sum< ::sineva_nav::Relocation > 
template<>
struct MD5Sum< ::sineva_nav::RelocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::Relocation >::value();
  }
  static const char* value(const ::sineva_nav::RelocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::RelocationResponse> should match 
// service_traits::DataType< ::sineva_nav::Relocation > 
template<>
struct DataType< ::sineva_nav::RelocationResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::Relocation >::value();
  }
  static const char* value(const ::sineva_nav::RelocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_RELOCATION_H
