// Generated by gencpp from file sineva_nav/SaveMappingRequest.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_SAVEMAPPINGREQUEST_H
#define SINEVA_NAV_MESSAGE_SAVEMAPPINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sineva_nav
{
template <class ContainerAllocator>
struct SaveMappingRequest_
{
  typedef SaveMappingRequest_<ContainerAllocator> Type;

  SaveMappingRequest_()
    : save_signal()
    , save_path()  {
    }
  SaveMappingRequest_(const ContainerAllocator& _alloc)
    : save_signal(_alloc)
    , save_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _save_signal_type;
  _save_signal_type save_signal;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _save_path_type;
  _save_path_type save_path;





  typedef boost::shared_ptr< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMappingRequest_

typedef ::sineva_nav::SaveMappingRequest_<std::allocator<void> > SaveMappingRequest;

typedef boost::shared_ptr< ::sineva_nav::SaveMappingRequest > SaveMappingRequestPtr;
typedef boost::shared_ptr< ::sineva_nav::SaveMappingRequest const> SaveMappingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sineva_nav::SaveMappingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sineva_nav

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sineva_nav': ['/home/nuc/code/Sineva_Code-delivery/ssp/ros/src/sineva_nav/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a93006a36ccce7a0204e14031f918ad0";
  }

  static const char* value(const ::sineva_nav::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa93006a36ccce7a0ULL;
  static const uint64_t static_value2 = 0x204e14031f918ad0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sineva_nav/SaveMappingRequest";
  }

  static const char* value(const ::sineva_nav::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string save_signal\n\
string save_path\n\
";
  }

  static const char* value(const ::sineva_nav::SaveMappingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.save_signal);
      stream.next(m.save_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMappingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sineva_nav::SaveMappingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sineva_nav::SaveMappingRequest_<ContainerAllocator>& v)
  {
    s << indent << "save_signal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.save_signal);
    s << indent << "save_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.save_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_SAVEMAPPINGREQUEST_H
