// Generated by gencpp from file sineva_nav/SaveMapping.msg
// DO NOT EDIT!


#ifndef SINEVA_NAV_MESSAGE_SAVEMAPPING_H
#define SINEVA_NAV_MESSAGE_SAVEMAPPING_H

#include <ros/service_traits.h>


#include <sineva_nav/SaveMappingRequest.h>
#include <sineva_nav/SaveMappingResponse.h>


namespace sineva_nav
{

struct SaveMapping
{

typedef SaveMappingRequest Request;
typedef SaveMappingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMapping
} // namespace sineva_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sineva_nav::SaveMapping > {
  static const char* value()
  {
    return "5fe2de99ca88e365b15343be61af7c60";
  }

  static const char* value(const ::sineva_nav::SaveMapping&) { return value(); }
};

template<>
struct DataType< ::sineva_nav::SaveMapping > {
  static const char* value()
  {
    return "sineva_nav/SaveMapping";
  }

  static const char* value(const ::sineva_nav::SaveMapping&) { return value(); }
};


// service_traits::MD5Sum< ::sineva_nav::SaveMappingRequest> should match 
// service_traits::MD5Sum< ::sineva_nav::SaveMapping > 
template<>
struct MD5Sum< ::sineva_nav::SaveMappingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SaveMapping >::value();
  }
  static const char* value(const ::sineva_nav::SaveMappingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SaveMappingRequest> should match 
// service_traits::DataType< ::sineva_nav::SaveMapping > 
template<>
struct DataType< ::sineva_nav::SaveMappingRequest>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SaveMapping >::value();
  }
  static const char* value(const ::sineva_nav::SaveMappingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sineva_nav::SaveMappingResponse> should match 
// service_traits::MD5Sum< ::sineva_nav::SaveMapping > 
template<>
struct MD5Sum< ::sineva_nav::SaveMappingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sineva_nav::SaveMapping >::value();
  }
  static const char* value(const ::sineva_nav::SaveMappingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sineva_nav::SaveMappingResponse> should match 
// service_traits::DataType< ::sineva_nav::SaveMapping > 
template<>
struct DataType< ::sineva_nav::SaveMappingResponse>
{
  static const char* value()
  {
    return DataType< ::sineva_nav::SaveMapping >::value();
  }
  static const char* value(const ::sineva_nav::SaveMappingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SINEVA_NAV_MESSAGE_SAVEMAPPING_H
