(cl:in-package sineva_nav-msg)
(cl:export '(HEADER-VAL
          HEADER
          POWER-VAL
          POWER
          IENCODER_L-VAL
          IENCODER_L
          IENCODER_R-VAL
          IENCODER_R
          IVOLTAGE-VAL
          IVOLTAGE
          ICURRENT-VAL
          ICURRENT
          QUANTITY-VAL
          QUANTITY
          BATTEMP-VAL
          BATTEMP
          CAPICITY-VAL
          CAPICITY
          ILEFTMOTOR-VAL
          ILEFTMOTOR
          IRIGHTMOTOR-VAL
          IRIGHTMOTOR
          ISCRAM-VAL
          ISCRAM
          ICRASH-VAL
          ICRASH
          IOSTATUS-VAL
          IOSTATUS
          ICHARGE-VAL
          ICHARGE
          ISHUTDOWN-VAL
          ISHUTDOWN
          IRESET-VAL
          IRESET
          IAUTO-VAL
          IAUTO
          ILIFT-VAL
          ILIFT
))